[project]
authors = ["semiwaker <semiwaker@163.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "UVLLM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fix = { cmd = [
    "python",
    "UVLLM/Main.py",
], env = { "PYTHONPATH" = "Strider/libs/Pyverilog" } }

rm-cirfix = { cmd = ["rm", "-rf", "benchmarks/cirfix_benchmarks"] }
cp-cirfix = { cmd = [
    "cp",
    "-r",
    "cirfix_benchmarks",
    "benchmarks/",
], depends-on = [
    "rm-cirfix",
] }
fix-cirfix = { cmd = [
    "python",
    "UVLLM/Main.py",
    "-b",
    "cirfix_benchmarks",
], env = { "PYTHONPATH" = "Strider/libs/Pyverilog" }, depends-on = [
    "cp-cirfix",
] }

[dependencies]
verilator = ">=5.34,<6"
iverilog = ">=11.0,<12"
python = ">=3.13.3,<3.14"
verible = ">=0.0_3667_g88d12889,<0.0_3668"

[pypi-dependencies]
boto3 = "==1.34.1"
func_timeout = "==4.3.5"
Jinja2 = "==3.1.2"
MarkupSafe = "==2.1.1"
ply = "==3.11"
# pyverilog = "==1.3.0"
setuptools = "==60.2.0"
wheel = "==0.37.1"
pyvcd = "==0.4.0"
dataclasses = "==0.6"
openai = "==1.52.1"
vcdvcd = "==2.3.4"
tomli = "==2.0.1"
pytest = "==7.4.4"
pytest-xdist = "==3.5.0" # for testing
# annotated-types = "==0.6.0"
# anyio = "==4.3.0"
# asttokens = "==2.4.1"
# certifi = "==2024.2.2"
# colorama = "==0.4.6"
# comm = "==0.2.2"
# debugpy = "==1.8.1"
# decorator = "==5.1.1"
# distro = "==1.9.0"
# executing = "==2.0.1"
# h11 = "==0.14.0"
# httpcore = "==1.0.4"
# httpx = "==0.27.0"
# idna = "==3.6"
# ipykernel = "==6.29.3"
# ipython = "==8.22.2"
# jedi = "==0.19.1"
# jupyter_client = "==8.6.1"
# jupyter_core = "==5.7.2"
# matplotlib-inline = "==0.1.6"
# nest-asyncio = "==1.6.0"
# packaging = "==24.0"
# parso = "==0.8.3"
# platformdirs = "==4.2.0"
# prompt-toolkit = "==3.0.43"
# psutil = "==5.9.8"
# pure-eval = "==0.2.2"
# # pydantic = "==2.6.4"
# # pydantic_core = "==2.16.3"
# Pygments = "==2.17.2"
# python-dateutil = "==2.9.0.post0"
# # pywin32 = "==310"
# pyzmq = "==25.1.2"
# six = "==1.16.0"
# sniffio = "==1.3.1"
# stack-data = "==0.6.3"
# tornado = "==6.4"
# tqdm = "==4.66.2"
# traitlets = "==5.14.2"
# wcwidth = "==0.2.13"
